import os
import rtconfig
from building import *


Import('STM32_SDK_ROOT')
Import('RTT_ROOT')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32f1xx_hal_msp.c
''')

path =  [cwd]
path += [cwd + '/CubeMX_Config/Inc']

# STM32_SDK_ROOT路径：
# C:\Users\18452\Documents\GitHub\DemoProject\RTTHREAD\rtos\platform\stm32_libraries
src += [STM32_SDK_ROOT + '\STM32F1xx_HAL\CMSIS\Device\ST\STM32F1xx\Source\Templates\gcc\startup_stm32f103xe.s']

# STM32F100xB || STM32F100xE || STM32F101x6
# STM32F101xB || STM32F101xE || STM32F101xG
# STM32F102x6 || STM32F102xB || STM32F103x6
# STM32F103xB || STM32F103xE || STM32F103xG
# STM32F105xC || STM32F107xC)
# You can select chips from the list above
CPPDEFINES = ['STM32F103xE']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
# include HAL libraries
group.extend(SConscript(os.path.join(STM32_SDK_ROOT, 'STM32F1xx_HAL', 'SConscript')))
# include drivers
group.extend(SConscript(os.path.join(RTT_ROOT, 'bsp\stm32\libraries\HAL_Drivers', 'SConscript')))
Return('group')
